[book]
title = "HDanke's Geometry Dash Editor Documentation"
src = "docs"

[build]
build-dir = "site"

[output.html]
math = true
no-section-label = true
sidebar-header-nav = false
git-repository-url = "https://github.com/UHDanke/gd_docs/"

[output.html.fold]
enable = true
level = 0 
