[book]
title = "HDanke's Geometry Dash Docs"
src = "docs"

[output.html]
smart-punctuation = true
mathjax-support = true
no-section-label = true
sidebar-header-nav = false
git-repository-url = "https://github.com/UHDanke/gd_docs/"

[output.html.fold]
enable = true
level = 0

[build]
build-dir = "site"
