[book]
title = "HDanke's Geometry Dash Docs"
src = "docs"

[build]
build-dir = "site"

[output]

[output.html]
math = true
section-label = false
sidebar-header-nav = false
git-repository-url = "https://github.com/UHDanke/gd_docs/"

[output.html.fold]
enable = true
level = 0
