name: Build mdBook

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write  # REQUIRED to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache mdBook
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            target
          key: mdbook-${{ runner.os }}-${{ hashFiles('**/book.toml') }}
          restore-keys: |
            mdbook-${{ runner.os }}-

      - name: Install mdBook
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install mdbook

      - name: Add Cargo bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build Documentation
        run: mdbook build

      # Deploy
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
